[package]
name = "project-profen"
version = "0.1.0"
edition = "2024"

[dependencies]
mlua = { version = "0.11.5", features = ["lua54", "vendored"]}
bytemuck = "1"
ultraviolet = "0.7"
beryllium = "0.13.3"
imagine = "0.0.5"
ogl33 = { version = "0.2", features = ["debug_error_checks"]}

